### ISSUE TITLE
Bug with lambda expressions

### ISSUE THREAD

**Issue by thatsed** [tox-dev/sphinx-autodoc-typehints#148]
The following snippet, took from [django-guardian](https://github.com/django-guardian/django-guardian):
```python
# guardian/__init__.py
...
setattr(User, 'add_obj_perm',
        lambda self, perm, obj: UserObjectPermission.objects.assign_perm(perm, self, obj))
```
 throws the following exception for Sphinx up to version 3.0.4:
```
Exception occurred:
  File "/usr/local/lib/python3.8/ast.py", line 47, in parse
    return compile(source, filename, mode, flags,
  File "<unknown>", line 1
    lambda self, perm, obj: UserObjectPermission.objects.assign_perm(perm, self, obj))
                                                                                     ^
SyntaxError: unmatched ')'
The full traceback has been saved in /tmp/sphinx-err-7sma3mgu.log, if you want to report the issue to the developers.
```
<details>
  <summary>Full traceback</summary>
  
```
# Sphinx version: 3.0.3
# Python version: 3.8.3 (CPython)
# Docutils version: 0.16 release
# Jinja2 version: 2.11.2
# Last messages:
#   reading sources... [ 41%] *redacted*
#   reading sources... [ 45%] *redacted*
#   reading sources... [ 50%] *redacted*
#   reading sources... [ 54%] *redacted*
#   reading sources... [ 58%] *redacted*
#   reading sources... [ 62%] *redacted*
#   reading sources... [ 66%] *redacted*
#   reading sources... [ 70%] *redacted*
#   reading sources... [ 75%] *redacted*
#   reading sources... [ 79%] *redacted*
# Loaded extensions:
#   sphinx.ext.mathjax (3.0.3) from /usr/local/lib/python3.8/site-packages/sphinx/ext/mathjax.py
#   sphinxcontrib.applehelp (1.0.2) from /usr/local/lib/python3.8/site-packages/sphinxcontrib/applehelp/__init__.py
#   sphinxcontrib.devhelp (1.0.2) from /usr/local/lib/python3.8/site-packages/sphinxcontrib/devhelp/__init__.py
#   sphinxcontrib.htmlhelp (1.0.3) from /usr/local/lib/python3.8/site-packages/sphinxcontrib/htmlhelp/__init__.py
#   sphinxcontrib.serializinghtml (1.1.4) from /usr/local/lib/python3.8/site-packages/sphinxcontrib/serializinghtml/__init__.py
#   sphinxcontrib.qthelp (1.0.3) from /usr/local/lib/python3.8/site-packages/sphinxcontrib/qthelp/__init__.py
#   alabaster (0.7.12) from /usr/local/lib/python3.8/site-packages/alabaster/__init__.py
#   sphinx.ext.autodoc.type_comment (3.0.3) from /usr/local/lib/python3.8/site-packages/sphinx/ext/autodoc/type_comment.py
#   sphinx.ext.autodoc (3.0.3) from /usr/local/lib/python3.8/site-packages/sphinx/ext/autodoc/__init__.py
#   sphinx.ext.viewcode (3.0.3) from /usr/local/lib/python3.8/site-packages/sphinx/ext/viewcode.py
#   sphinx.ext.todo (3.0.3) from /usr/local/lib/python3.8/site-packages/sphinx/ext/todo.py
#   sphinx_autodoc_typehints (unknown version) from /usr/local/lib/python3.8/site-packages/sphinx_autodoc_typehints.py
#   celery.contrib.sphinx (unknown version) from /usr/local/lib/python3.8/site-packages/celery/contrib/sphinx.py
#   sphinxcontrib_django (unknown version) from /usr/local/lib/python3.8/site-packages/sphinxcontrib_django/__init__.py
#   sphinx_rtd_theme (unknown version) from /usr/local/lib/python3.8/site-packages/sphinx_rtd_theme/__init__.py
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/sphinx/cmd/build.py", line 280, in build_main
    app.build(args.force_all, filenames)
  File "/usr/local/lib/python3.8/site-packages/sphinx/application.py", line 348, in build
    self.builder.build_update()
  File "/usr/local/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 297, in build_update
    self.build(to_build,
  File "/usr/local/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 311, in build
    updated_docnames = set(self.read())
  File "/usr/local/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 418, in read
    self._read_serial(docnames)
  File "/usr/local/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 439, in _read_serial
    self.read_doc(docname)
  File "/usr/local/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 479, in read_doc
    doctree = read_doc(self.app, self.env, self.env.doc2path(docname))
  File "/usr/local/lib/python3.8/site-packages/sphinx/io.py", line 221, in read_doc
    pub.publish()
  File "/usr/local/lib/python3.8/site-packages/docutils/core.py", line 217, in publish
    self.document = self.reader.read(self.source, self.parser,
  File "/usr/local/lib/python3.8/site-packages/sphinx/io.py", line 126, in read
    self.parse()
  File "/usr/local/lib/python3.8/site-packages/docutils/readers/__init__.py", line 77, in parse
    self.parser.parse(self.input, document)
  File "/usr/local/lib/python3.8/site-packages/sphinx/parsers.py", line 102, in parse
    self.statemachine.run(inputlines, document, inliner=self.inliner)
  File "/usr/local/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 170, in run
    results = StateMachineWS.run(self, input_lines, input_offset,
  File "/usr/local/lib/python3.8/site-packages/docutils/statemachine.py", line 241, in run
    context, next_state, result = self.check_line(
  File "/usr/local/lib/python3.8/site-packages/docutils/statemachine.py", line 459, in check_line
    return method(match, context, next_state)
  File "/usr/local/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 2769, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "/usr/local/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 327, in section
    self.new_subsection(title, lineno, messages)
  File "/usr/local/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 393, in new_subsection
    newabsoffset = self.nested_parse(
  File "/usr/local/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 281, in nested_parse
    state_machine.run(block, input_offset, memo=self.memo,
  File "/usr/local/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 196, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/usr/local/lib/python3.8/site-packages/docutils/statemachine.py", line 241, in run
    context, next_state, result = self.check_line(
  File "/usr/local/lib/python3.8/site-packages/docutils/statemachine.py", line 459, in check_line
    return method(match, context, next_state)
  File "/usr/local/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 2769, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "/usr/local/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 327, in section
    self.new_subsection(title, lineno, messages)
  File "/usr/local/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 393, in new_subsection
    newabsoffset = self.nested_parse(
  File "/usr/local/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 281, in nested_parse
    state_machine.run(block, input_offset, memo=self.memo,
  File "/usr/local/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 196, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/usr/local/lib/python3.8/site-packages/docutils/statemachine.py", line 241, in run
    context, next_state, result = self.check_line(
  File "/usr/local/lib/python3.8/site-packages/docutils/statemachine.py", line 459, in check_line
    return method(match, context, next_state)
  File "/usr/local/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 2342, in explicit_markup
    nodelist, blank_finish = self.explicit_construct(match)
  File "/usr/local/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 2354, in explicit_construct
    return method(self, expmatch)
  File "/usr/local/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 2096, in directive
    return self.run_directive(
  File "/usr/local/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 2146, in run_directive
    result = directive_instance.run()
  File "/usr/local/lib/python3.8/site-packages/sphinx/ext/autodoc/directive.py", line 146, in run
    documenter.generate(more_content=self.content)
  File "/usr/local/lib/python3.8/site-packages/sphinx/ext/autodoc/__init__.py", line 775, in generate
    self.document_members(all_members)
  File "/usr/local/lib/python3.8/site-packages/sphinx/ext/autodoc/__init__.py", line 695, in document_members
    documenter.generate(
  File "/usr/local/lib/python3.8/site-packages/sphinx/ext/autodoc/__init__.py", line 1299, in generate
    return super().generate(more_content=more_content,
  File "/usr/local/lib/python3.8/site-packages/sphinx/ext/autodoc/__init__.py", line 775, in generate
    self.document_members(all_members)
  File "/usr/local/lib/python3.8/site-packages/sphinx/ext/autodoc/__init__.py", line 1290, in document_members
    super().document_members(all_members)
  File "/usr/local/lib/python3.8/site-packages/sphinx/ext/autodoc/__init__.py", line 695, in document_members
    documenter.generate(
  File "/usr/local/lib/python3.8/site-packages/sphinx/ext/autodoc/__init__.py", line 772, in generate
    self.add_content(more_content)
  File "/usr/local/lib/python3.8/site-packages/sphinx/ext/autodoc/__init__.py", line 481, in add_content
    for i, line in enumerate(self.process_doc(docstrings)):
  File "/usr/local/lib/python3.8/site-packages/sphinx/ext/autodoc/__init__.py", line 449, in process_doc
    self.env.app.emit('autodoc-process-docstring',
  File "/usr/local/lib/python3.8/site-packages/sphinx/application.py", line 445, in emit
    return self.events.emit(event, *args)
  File "/usr/local/lib/python3.8/site-packages/sphinx/events.py", line 107, in emit
    results.append(listener.handler(self.app, *args))
  File "/usr/local/lib/python3.8/site-packages/sphinx_autodoc_typehints.py", line 364, in process_docstring
    type_hints = get_all_type_hints(obj, name)
  File "/usr/local/lib/python3.8/site-packages/sphinx_autodoc_typehints.py", line 219, in get_all_type_hints
    rv = backfill_type_hints(obj, name)
  File "/usr/local/lib/python3.8/site-packages/sphinx_autodoc_typehints.py", line 260, in backfill_type_hints
    obj_ast = ast.parse(textwrap.dedent(inspect.getsource(obj)), **parse_kwargs)
  File "/usr/local/lib/python3.8/ast.py", line 47, in parse
    return compile(source, filename, mode, flags,
  File "<unknown>", line 1
    lambda self, perm, obj: UserObjectPermission.objects.assign_perm(perm, self, obj))
```
</details>

while in sphinx >= 3.1.0:
```
Extension error:
Handler <function process_docstring at 0x7f2ae25de160> for event 'autodoc-process-docstring' threw an exception
make: *** [Makefile:20: html] Error 2
```
I suspect the lambda definition is messing with the type annotation parsing.
The same behavior is replicated with Python 3.8 and only `sphinx.ext.autodoc` and `sphinx_autodoc_typehints` in `extensions` (as per docs).

**Comment by agronholm** [comment]
I am not able to reproduce the problem using a cloned django-guardian repository and these exact Sphinx and Python versions.
Please provide exact repro instructions, starting from the creation of a new virtualenv.

**Comment by agronholm** [comment]
If you don't mind, please also test if using `ast.parse()` works with the problematic source file on your end.

**Comment by thatsed** [comment]
> I am not able to reproduce the problem using a cloned django-guardian repository and these exact Sphinx and Python versions.

Neither am I unfurtunately. I tried setting up a new django project and doing (more or less) the same things the first (close sourced) one did. Could not replicate.

> please also test if using ast.parse() works with the problematic source file on your end.

Somehow, `textwrap.dedent(inspect.getsource(obj))` (line 260) will take value `lambda self, perm, obj: UserObjectPermission.objects.assign_perm(perm, self, obj))`, which is syntactically wrong due to the last parenthesis. That is what `ast.parse()` is complaining about, but the real issue is how did that string get there in the first place.

I am giving up on the issue, due to a lack of knowledge on the matter. I've fixed it for my use case by simply excepting `SyntaxError`.

### Workaround
```python
# sphinx_autodoc_typehints.py, line 259
    ...
    try:
        obj_ast = ast.parse(textwrap.dedent(inspect.getsource(obj)), **parse_kwargs)
    except (OSError, TypeError, SyntaxError):
        return {}
    ...
```

<hr>

I'll note some things, hoping they may be useful:

- I am overriding the default django user model with guardian active as an auth backend
- The bug still occurs even if the module is not being imported
- Only the `models.py` module seems to trigger the docs generation for guardian, but no class extends any of its. So I don't know how it got involved in my docs, honestly. Again, I failed to replicate this behavior.
- The built html files will include a `_modules`  directory that includes `guardian` and its docs generated, while my replication test did not
- Catching the SyntaxError apparently does not produce side effects

Thank you for your time, have a good one.

**Comment by thatsed** [comment]
As it stands, lambda expressions seem to be completely unrelated to the issue. You may want to change this issue's title; I'm leaving it at your own discretion.

**Comment by jakevdp** [comment]
I've run into this recently as well; I think the issue is that `inspect.getsource()` does not always return a complete/valid code snippet. Here's a minimal example:
```python
In [1]: import inspect                                                                                                                                                               

In [2]: func = (lambda x: x)( 
   ...:   lambda x: x)                                                                                                                                                               

In [3]: inspect.getsource(func)                                                                                                                                                      
Out[3]: '  lambda x: x)\n'
```
This means that the result here fails to parse: https://github.com/agronholm/sphinx-autodoc-typehints/blob/49face656c51e370b68108a4a59c7032ed398a2e/sphinx_autodoc_typehints.py#L311-L315

and raises a `SyntaxError`, which is not caught by the current try/except block.

I think the easiest fix would be to also catch `SyntaxError` in line 314.

**Comment by gaborbernat** [comment]
This has now been fixed.
