### ISSUE TITLE
Python 3.8.5 singledispatchmethod Issues

### ISSUE THREAD

**Issue by liveFreeOrCode** [tox-dev/sphinx-autodoc-typehints#152]
I'm having trouble with [singledispatchmethod](https://docs.python.org/3/library/functools.html#functools.singledispatchmethod).

Code:
```
from functools import singledispatchmethod


class Test:
    @singledispatchmethod
    def test(self, event):
        pass

    @test.register
    def test_int(self, event: int):
        print("int")

    @test.register
    def test_str(self, event: str):
        print("str")
```

Running `sphinx-build -d _build/doctrees -b html . _build/html -W -T --keep-going`
```
# Sphinx version: 3.0.4
# Python version: 3.8.5 (CPython)
# Docutils version: 0.15.2 release
# Jinja2 version: 2.11.2
# Last messages:
#   reading sources... [ 42%] ref/test
# Loaded extensions:
#   sphinx.ext.mathjax (3.0.4) from /home/matt/dev/test/.tox/docs/lib/python3.8/site-packages/sphinx/ext/mathjax.py
#   sphinxcontrib.applehelp (1.0.2) from /home/matt/dev/test/.tox/docs/lib/python3.8/site-packages/sphinxcontrib/applehelp/__init__.py
#   sphinxcontrib.devhelp (1.0.2) from /home/matt/dev/test/.tox/docs/lib/python3.8/site-packages/sphinxcontrib/devhelp/__init__.py
#   sphinxcontrib.htmlhelp (1.0.3) from /home/matt/dev/test/.tox/docs/lib/python3.8/site-packages/sphinxcontrib/htmlhelp/__init__.py
#   sphinxcontrib.serializinghtml (1.1.4) from /home/matt/dev/test/.tox/docs/lib/python3.8/site-packages/sphinxcontrib/serializinghtml/__init__.py
#   sphinxcontrib.qthelp (1.0.3) from /home/matt/dev/test/.tox/docs/lib/python3.8/site-packages/sphinxcontrib/qthelp/__init__.py
#   alabaster (0.7.12) from /home/matt/dev/test/.tox/docs/lib/python3.8/site-packages/alabaster/__init__.py
#   sphinx.ext.autodoc.type_comment (3.0.4) from /home/matt/dev/test/.tox/docs/lib/python3.8/site-packages/sphinx/ext/autodoc/type_comment.py
#   sphinx.ext.autodoc (3.0.4) from /home/matt/dev/test/.tox/docs/lib/python3.8/site-packages/sphinx/ext/autodoc/__init__.py
#   sphinx.ext.intersphinx (3.0.4) from /home/matt/dev/test/.tox/docs/lib/python3.8/site-packages/sphinx/ext/intersphinx.py
#   sphinx.ext.viewcode (3.0.4) from /home/matt/dev/test/.tox/docs/lib/python3.8/site-packages/sphinx/ext/viewcode.py
#   sphinx.ext.extlinks (3.0.4) from /home/matt/dev/test/.tox/docs/lib/python3.8/site-packages/sphinx/ext/extlinks.py
#   sphinx.ext.todo (3.0.4) from /home/matt/dev/test/.tox/docs/lib/python3.8/site-packages/sphinx/ext/todo.py
#   sphinx_autodoc_typehints (unknown version) from /home/matt/dev/test/.tox/docs/lib/python3.8/site-packages/sphinx_autodoc_typehints.py
#   IPython.sphinxext.ipython_console_highlighting (unknown version) from /home/matt/dev/test/.tox/docs/lib/python3.8/site-packages/IPython/sphinxext/ipython_console_highlighting.py
#   ghlink (unknown version) from /home/matt/dev/test/docs/_extensions/ghlink.py
Traceback (most recent call last):
  File "/home/matt/dev/test/.tox/docs/lib/python3.8/site-packages/sphinx/cmd/build.py", line 280, in build_main
    app.build(args.force_all, filenames)
  File "/home/matt/dev/test/.tox/docs/lib/python3.8/site-packages/sphinx/application.py", line 348, in build
    self.builder.build_update()
  File "/home/matt/dev/test/.tox/docs/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 297, in build_update
    self.build(to_build,
  File "/home/matt/dev/test/.tox/docs/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 311, in build
    updated_docnames = set(self.read())
  File "/home/matt/dev/test/.tox/docs/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 418, in read
    self._read_serial(docnames)
  File "/home/matt/dev/test/.tox/docs/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 439, in _read_serial
    self.read_doc(docname)
  File "/home/matt/dev/test/.tox/docs/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 479, in read_doc
    doctree = read_doc(self.app, self.env, self.env.doc2path(docname))
  File "/home/matt/dev/test/.tox/docs/lib/python3.8/site-packages/sphinx/io.py", line 221, in read_doc
    pub.publish()
  File "/home/matt/dev/test/.tox/docs/lib/python3.8/site-packages/docutils/core.py", line 216, in publish
    self.document = self.reader.read(self.source, self.parser,
  File "/home/matt/dev/test/.tox/docs/lib/python3.8/site-packages/sphinx/io.py", line 126, in read
    self.parse()
  File "/home/matt/dev/test/.tox/docs/lib/python3.8/site-packages/docutils/readers/__init__.py", line 77, in parse
    self.parser.parse(self.input, document)
  File "/home/matt/dev/test/.tox/docs/lib/python3.8/site-packages/sphinx/parsers.py", line 102, in parse
    self.statemachine.run(inputlines, document, inliner=self.inliner)
  File "/home/matt/dev/test/.tox/docs/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 170, in run
    results = StateMachineWS.run(self, input_lines, input_offset,
  File "/home/matt/dev/test/.tox/docs/lib/python3.8/site-packages/docutils/statemachine.py", line 238, in run
    context, next_state, result = self.check_line(
  File "/home/matt/dev/test/.tox/docs/lib/python3.8/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/home/matt/dev/test/.tox/docs/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 2771, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "/home/matt/dev/test/.tox/docs/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 327, in section
    self.new_subsection(title, lineno, messages)
  File "/home/matt/dev/test/.tox/docs/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 393, in new_subsection
    newabsoffset = self.nested_parse(
  File "/home/matt/dev/test/.tox/docs/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 281, in nested_parse
    state_machine.run(block, input_offset, memo=self.memo,
  File "/home/matt/dev/test/.tox/docs/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 196, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/home/matt/dev/test/.tox/docs/lib/python3.8/site-packages/docutils/statemachine.py", line 238, in run
    context, next_state, result = self.check_line(
  File "/home/matt/dev/test/.tox/docs/lib/python3.8/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/home/matt/dev/test/.tox/docs/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 2344, in explicit_markup
    nodelist, blank_finish = self.explicit_construct(match)
  File "/home/matt/dev/test/.tox/docs/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 2356, in explicit_construct
    return method(self, expmatch)
  File "/home/matt/dev/test/.tox/docs/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 2098, in directive
    return self.run_directive(
  File "/home/matt/dev/test/.tox/docs/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 2148, in run_directive
    result = directive_instance.run()
  File "/home/matt/dev/test/.tox/docs/lib/python3.8/site-packages/sphinx/ext/autodoc/directive.py", line 146, in run
    documenter.generate(more_content=self.content)
  File "/home/matt/dev/test/.tox/docs/lib/python3.8/site-packages/sphinx/ext/autodoc/__init__.py", line 775, in generate
    self.document_members(all_members)
  File "/home/matt/dev/test/.tox/docs/lib/python3.8/site-packages/sphinx/ext/autodoc/__init__.py", line 695, in document_members
    documenter.generate(
  File "/home/matt/dev/test/.tox/docs/lib/python3.8/site-packages/sphinx/ext/autodoc/__init__.py", line 1299, in generate
    return super().generate(more_content=more_content,
  File "/home/matt/dev/test/.tox/docs/lib/python3.8/site-packages/sphinx/ext/autodoc/__init__.py", line 775, in generate
    self.document_members(all_members)
  File "/home/matt/dev/test/.tox/docs/lib/python3.8/site-packages/sphinx/ext/autodoc/__init__.py", line 1290, in document_members
    super().document_members(all_members)
  File "/home/matt/dev/test/.tox/docs/lib/python3.8/site-packages/sphinx/ext/autodoc/__init__.py", line 695, in document_members
    documenter.generate(
  File "/home/matt/dev/test/.tox/docs/lib/python3.8/site-packages/sphinx/ext/autodoc/__init__.py", line 765, in generate
    self.add_directive_header(sig)
  File "/home/matt/dev/test/.tox/docs/lib/python3.8/site-packages/sphinx/ext/autodoc/__init__.py", line 1520, in add_directive_header
    documenter.format_signature()),
  File "/home/matt/dev/test/.tox/docs/lib/python3.8/site-packages/sphinx/ext/autodoc/__init__.py", line 981, in format_signature
    return super().format_signature(**kwargs)  # type: ignore
  File "/home/matt/dev/test/.tox/docs/lib/python3.8/site-packages/sphinx/ext/autodoc/__init__.py", line 405, in format_signature
    result = self.env.events.emit_firstresult('autodoc-process-signature',
  File "/home/matt/dev/test/.tox/docs/lib/python3.8/site-packages/sphinx/events.py", line 115, in emit_firstresult
    for result in self.emit(name, *args):
  File "/home/matt/dev/test/.tox/docs/lib/python3.8/site-packages/sphinx/events.py", line 107, in emit
    results.append(listener.handler(self.app, *args))
  File "/home/matt/dev/test/.tox/docs/lib/python3.8/site-packages/sphinx_autodoc_typehints.py", line 176, in process_signature
    if inspect.isclass(original_obj) or (what == 'method' and name.endswith('.__init__')):
AttributeError: 'NoneType' object has no attribute 'endswith'
```

**Comment by gaborbernat** [comment]
Please check again with latest release and report back if the problem is still active.
