### ISSUE TITLE
Building documentation fails with "format_annotation() got an unexpected keyword argument 'simplify_optional_unions'"

### ISSUE THREAD

**Issue by phijor** [tox-dev/sphinx-autodoc-typehints#172]
**Describe the bug**

When building our documentation with `sphinx-autodoc-typehints==1.12.0`, it fails with the following exception:

```
Extension error (sphinx_autodoc_typehints):
Handler <function process_docstring at 0x7f0a42e2e1f0> for event 'autodoc-process-docstring' threw an exception (exception: format_annotation() got an unexpected keyword argument 'simplify_optional_unions')
```

Here is a link to the failed CI run: https://github.com/metricq/metricq-python/runs/2351537093

Pinning the extension to a version `<1.12.0` fixes the issue: https://github.com/metricq/metricq-python/runs/2351749362

For each of the runs, you can see the list of installed packages under the step _Installing dependencies_.

**To Reproduce**

_TBD: currently trying to slim down our docs to a MWE_

**Expected behavior**

Successfully build the documentation.

**Additional context**

<details>
    <summary> Full traceback of `sphinx-build -P` run </summary>

```
Traceback (most recent call last):
  File "/home/phijor/etc/data/virtualenvs/metricq-python-W5923aFJ/lib/python3.9/site-packages/sphinx/events.py", line 111, in emit
    results.append(listener.handler(self.app, *args))
  File "/home/phijor/etc/data/virtualenvs/metricq-python-W5923aFJ/lib/python3.9/site-packages/sphinx_autodoc_typehints.py", line 425, in process_docstring
    formatted_annotation = format_annotation(
TypeError: format_annotation() got an unexpected keyword argument 'simplify_optional_unions'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/phijor/etc/data/virtualenvs/metricq-python-W5923aFJ/lib/python3.9/site-packages/sphinx/cmd/build.py", line 280, in build_main
    app.build(args.force_all, filenames)
  File "/home/phijor/etc/data/virtualenvs/metricq-python-W5923aFJ/lib/python3.9/site-packages/sphinx/application.py", line 352, in build
    self.builder.build_update()
  File "/home/phijor/etc/data/virtualenvs/metricq-python-W5923aFJ/lib/python3.9/site-packages/sphinx/builders/__init__.py", line 296, in build_update
    self.build(to_build,
  File "/home/phijor/etc/data/virtualenvs/metricq-python-W5923aFJ/lib/python3.9/site-packages/sphinx/builders/__init__.py", line 310, in build
    updated_docnames = set(self.read())
  File "/home/phijor/etc/data/virtualenvs/metricq-python-W5923aFJ/lib/python3.9/site-packages/sphinx/builders/__init__.py", line 417, in read
    self._read_serial(docnames)
  File "/home/phijor/etc/data/virtualenvs/metricq-python-W5923aFJ/lib/python3.9/site-packages/sphinx/builders/__init__.py", line 438, in _read_serial
    self.read_doc(docname)
  File "/home/phijor/etc/data/virtualenvs/metricq-python-W5923aFJ/lib/python3.9/site-packages/sphinx/builders/__init__.py", line 478, in read_doc
    doctree = read_doc(self.app, self.env, self.env.doc2path(docname))
  File "/home/phijor/etc/data/virtualenvs/metricq-python-W5923aFJ/lib/python3.9/site-packages/sphinx/io.py", line 221, in read_doc
    pub.publish()
  File "/home/phijor/etc/data/virtualenvs/metricq-python-W5923aFJ/lib/python3.9/site-packages/docutils/core.py", line 217, in publish
    self.document = self.reader.read(self.source, self.parser,
  File "/home/phijor/etc/data/virtualenvs/metricq-python-W5923aFJ/lib/python3.9/site-packages/sphinx/io.py", line 126, in read
    self.parse()
  File "/home/phijor/etc/data/virtualenvs/metricq-python-W5923aFJ/lib/python3.9/site-packages/docutils/readers/__init__.py", line 77, in parse
    self.parser.parse(self.input, document)
  File "/home/phijor/etc/data/virtualenvs/metricq-python-W5923aFJ/lib/python3.9/site-packages/sphinx/parsers.py", line 104, in parse
    self.statemachine.run(inputlines, document, inliner=self.inliner)
  File "/home/phijor/etc/data/virtualenvs/metricq-python-W5923aFJ/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 170, in run
    results = StateMachineWS.run(self, input_lines, input_offset,
  File "/home/phijor/etc/data/virtualenvs/metricq-python-W5923aFJ/lib/python3.9/site-packages/docutils/statemachine.py", line 241, in run
    context, next_state, result = self.check_line(
  File "/home/phijor/etc/data/virtualenvs/metricq-python-W5923aFJ/lib/python3.9/site-packages/docutils/statemachine.py", line 459, in check_line
    return method(match, context, next_state)
  File "/home/phijor/etc/data/virtualenvs/metricq-python-W5923aFJ/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 2769, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "/home/phijor/etc/data/virtualenvs/metricq-python-W5923aFJ/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 327, in section
    self.new_subsection(title, lineno, messages)
  File "/home/phijor/etc/data/virtualenvs/metricq-python-W5923aFJ/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 393, in new_subsection
    newabsoffset = self.nested_parse(
  File "/home/phijor/etc/data/virtualenvs/metricq-python-W5923aFJ/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 281, in nested_parse
    state_machine.run(block, input_offset, memo=self.memo,
  File "/home/phijor/etc/data/virtualenvs/metricq-python-W5923aFJ/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 196, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/home/phijor/etc/data/virtualenvs/metricq-python-W5923aFJ/lib/python3.9/site-packages/docutils/statemachine.py", line 241, in run
    context, next_state, result = self.check_line(
  File "/home/phijor/etc/data/virtualenvs/metricq-python-W5923aFJ/lib/python3.9/site-packages/docutils/statemachine.py", line 459, in check_line
    return method(match, context, next_state)
  File "/home/phijor/etc/data/virtualenvs/metricq-python-W5923aFJ/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 2342, in explicit_markup
    nodelist, blank_finish = self.explicit_construct(match)
  File "/home/phijor/etc/data/virtualenvs/metricq-python-W5923aFJ/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 2354, in explicit_construct
    return method(self, expmatch)
  File "/home/phijor/etc/data/virtualenvs/metricq-python-W5923aFJ/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 2096, in directive
    return self.run_directive(
  File "/home/phijor/etc/data/virtualenvs/metricq-python-W5923aFJ/lib/python3.9/site-packages/docutils/parsers/rst/states.py", line 2146, in run_directive
    result = directive_instance.run()
  File "/home/phijor/etc/data/virtualenvs/metricq-python-W5923aFJ/lib/python3.9/site-packages/sphinx/ext/autodoc/directive.py", line 167, in run
    documenter.generate(more_content=self.content)
  File "/home/phijor/etc/data/virtualenvs/metricq-python-W5923aFJ/lib/python3.9/site-packages/sphinx/ext/autodoc/__init__.py", line 1726, in generate
    return super().generate(more_content=more_content,
  File "/home/phijor/etc/data/virtualenvs/metricq-python-W5923aFJ/lib/python3.9/site-packages/sphinx/ext/autodoc/__init__.py", line 967, in generate
    self.add_content(more_content)
  File "/home/phijor/etc/data/virtualenvs/metricq-python-W5923aFJ/lib/python3.9/site-packages/sphinx/ext/autodoc/__init__.py", line 1712, in add_content
    super().add_content(more_content)
  File "/home/phijor/etc/data/virtualenvs/metricq-python-W5923aFJ/lib/python3.9/site-packages/sphinx/ext/autodoc/__init__.py", line 628, in add_content
    for i, line in enumerate(self.process_doc(docstrings)):
  File "/home/phijor/etc/data/virtualenvs/metricq-python-W5923aFJ/lib/python3.9/site-packages/sphinx/ext/autodoc/__init__.py", line 569, in process_doc
    self.env.app.emit('autodoc-process-docstring',
  File "/home/phijor/etc/data/virtualenvs/metricq-python-W5923aFJ/lib/python3.9/site-packages/sphinx/application.py", line 462, in emit
    return self.events.emit(event, *args, allowed_exceptions=allowed_exceptions)
  File "/home/phijor/etc/data/virtualenvs/metricq-python-W5923aFJ/lib/python3.9/site-packages/sphinx/events.py", line 119, in emit
    raise ExtensionError(__("Handler %r for event %r threw an exception") %
sphinx.errors.ExtensionError: Handler <function process_docstring at 0x7efd53e3edc0> for event 'autodoc-process-docstring' threw an exception (exception: format_annotation() got an unexpected keyword argument 'simplify_optional_unions')
```
</details>

I would like to debug the issue further, but I do not know how to run `sphinx` under a debugger; Any pointers in this direction are appreciated.  Thank you for your work on this extension :)

**Comment by gaborbernat** [comment]
Can you please try again with latest version and report back if it's still a problem.
