### ISSUE TITLE
Error when typeguarded code is broken

### ISSUE THREAD

**Issue by flying-sheep** [tox-dev/sphinx-autodoc-typehints#206]
Trying to create a link to ``:class:`~sphinx.domains.python.PyTypedField` `` results in this faulty import line being executed by `_resolve_type_guarded_imports`

https://github.com/sphinx-doc/sphinx/blob/72d352f64ec97c2b15173cc1a191c0e80bde9630/sphinx/util/docfields.py#L24

```py
if TYPE_CHECKING:
    from sphinx.directive import ObjectDescription
```

(It should read <code>sphinx.directive<em>s</em></code>)

Traceback:

```pytb
Traceback (most recent call last):
  File "/home/phil/Dev/Python/venvs/single-cell/lib/python3.9/site-packages/sphinx/events.py", line 101, in emit
    results.append(listener.handler(self.app, *args))
  File "/home/phil/Dev/Python/venvs/single-cell/lib/python3.9/site-packages/sphinx_autodoc_typehints/__init__.py", line 449, in process_docstring
    type_hints = get_all_type_hints(obj, name)
  File "/home/phil/Dev/Python/venvs/single-cell/lib/python3.9/site-packages/sphinx_autodoc_typehints/__init__.py", line 263, in get_all_type_hints
    result = _get_type_hint(name, obj)
  File "/home/phil/Dev/Python/venvs/single-cell/lib/python3.9/site-packages/sphinx_autodoc_typehints/__init__.py", line 294, in _get_type_hint
    _resolve_type_guarded_imports(obj)
  File "/home/phil/Dev/Python/venvs/single-cell/lib/python3.9/site-packages/sphinx_autodoc_typehints/__init__.py", line 288, in _resolve_type_guarded_imports
    exec(module_code, obj.__globals__)
  File "<string>", line 2, in <module>
ModuleNotFoundError: No module named 'sphinx.directive'

The above exception was the direct cause of the following exception:

[…]

Extension error (sphinx_autodoc_typehints):
Handler <function process_docstring at 0x7faf762d7550> for event 'autodoc-process-docstring' threw an exception (exception: No module named 'sphinx.directive')
```

**Comment by flying-sheep** [comment]
It is, I think we should be robust against broken code like that: https://github.com/tox-dev/sphinx-autodoc-typehints/issues/206

**Comment by gaborbernat** [comment]
I believe we should warn at least for it 🤔to let the user know about it 🤔
