### ISSUE TITLE
Uncaught exception for C++ module

### ISSUE THREAD

**Issue by jmirabel** [tox-dev/sphinx-autodoc-typehints#209]
Although the documentation of `inspect.getsource` says
> An OSError is raised if the source code cannot be retrieved.

When I do
```
import inspect, sys
inspect.getsource(sys)
```
I get a TypeError and not a OSError, thus generating the documentation with a C++ module fails (it did not for earlier versions).

Catching both TypeError and OSError here fixes the issue:
https://github.com/tox-dev/sphinx-autodoc-typehints/blob/01b3a1abeac063a5530b96b78252aa17a93f040c/src/sphinx_autodoc_typehints/__init__.py#L286

**Comment by gaborbernat** [comment]
Can you provide a reproducible that generates a TypeError?

**Comment by jmirabel** [comment]
I can't provide the code I have an error with. I tried to replicate the error by adding a file `foo.rst` with
```rst
.. automodule:: sys
  :members:
```
I don't understand why it never calls `inspect.getsource` with argument `sys`. Any hints ?

**Comment by SimonHeybrock** [comment]
I just ran into the same issue (I think). Our project is using `pybind11` to build an extension module.

The error I got is:

```
Traceback (most recent call last):
  File "/home/simon/miniconda3/envs/scipp-developer/lib/python3.8/site-packages/sphinx/events.py", line 101, in emit
    results.append(listener.handler(self.app, *args))
  File "/home/simon/miniconda3/envs/scipp-developer/lib/python3.8/site-packages/sphinx_autodoc_typehints/__init__.py", line 498, in process_docstring
    type_hints = get_all_type_hints(obj, name)
  File "/home/simon/miniconda3/envs/scipp-developer/lib/python3.8/site-packages/sphinx_autodoc_typehints/__init__.py", line 307, in get_all_type_hints
    result = _get_type_hint(name, obj)
  File "/home/simon/miniconda3/envs/scipp-developer/lib/python3.8/site-packages/sphinx_autodoc_typehints/__init__.py", line 343, in _get_type_hint
    _resolve_type_guarded_imports(obj)
  File "/home/simon/miniconda3/envs/scipp-developer/lib/python3.8/site-packages/sphinx_autodoc_typehints/__init__.py", line 330, in _resolve_type_guarded_imports
    module_code = inspect.getsource(module)
  File "/home/simon/miniconda3/envs/scipp-developer/lib/python3.8/inspect.py", line 997, in getsource
    lines, lnum = getsourcelines(object)
  File "/home/simon/miniconda3/envs/scipp-developer/lib/python3.8/inspect.py", line 979, in getsourcelines
    lines, lnum = findsource(object)
  File "/home/simon/miniconda3/envs/scipp-developer/lib/python3.8/inspect.py", line 780, in findsource
    file = getsourcefile(object)
  File "/home/simon/miniconda3/envs/scipp-developer/lib/python3.8/inspect.py", line 696, in getsourcefile
    filename = getfile(object)
  File "/home/simon/miniconda3/envs/scipp-developer/lib/python3.8/inspect.py", line 659, in getfile
    raise TypeError('{!r} is a built-in module'.format(object))
TypeError: <module 'scipp._scipp.core'> is a built-in module
```

I locally tried the fix in #210 and it *does* solve the issue.

If it is useful, I can link to a code branch highlighting the problem, but it is far from a simple reproducer.

**Comment by jmirabel** [comment]
Our current solution is to stick to an earlier version (I don't recall which one exactly right now).

**Comment by SimonHeybrock** [comment]
Thanks, I installed 1.14.1 and it works. 1.15.3 does not.
