### ISSUE TITLE
1.18.1: build sphinx documentation of the `sphinx-toolbox` 3.0.0 fails

### ISSUE THREAD

**Issue by kloczek** [tox-dev/sphinx-autodoc-typehints#231]
Yeah looks like something is wrong with `sphinx-autodoc-typehints` module
```console
+ /usr/bin/sphinx-build -n -T -b man doc-source build/sphinx/man
Running Sphinx v4.5.0
loading translations [en]... done

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/cmd/build.py", line 272, in build_main
    app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
  File "/usr/lib/python3.8/site-packages/sphinx/application.py", line 223, in __init__
    self.setup_extension(extension)
  File "/usr/lib/python3.8/site-packages/sphinx/application.py", line 380, in setup_extension
    self.registry.load_extension(self, extname)
  File "/usr/lib/python3.8/site-packages/sphinx/registry.py", line 438, in load_extension
    metadata = setup(app)
  File "/home/tkloczko/rpmbuild/BUILD/sphinx-toolbox-3.0.0/./sphinx_toolbox/__init__.py", line 95, in setup
    app.setup_extension("sphinx_toolbox.more_autodoc.autoprotocol")
  File "/usr/lib/python3.8/site-packages/sphinx/application.py", line 380, in setup_extension
    self.registry.load_extension(self, extname)
  File "/usr/lib/python3.8/site-packages/sphinx/registry.py", line 425, in load_extension
    mod = import_module(extname)
  File "/usr/lib64/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/tkloczko/rpmbuild/BUILD/sphinx-toolbox-3.0.0/./sphinx_toolbox/more_autodoc/autoprotocol.py", line 153, in <module>
    from sphinx_toolbox.more_autodoc.generic_bases import _add_generic_bases
  File "/home/tkloczko/rpmbuild/BUILD/sphinx-toolbox-3.0.0/./sphinx_toolbox/more_autodoc/generic_bases.py", line 85, in <module>
    from sphinx_toolbox.more_autodoc.typehints import format_annotation
  File "/home/tkloczko/rpmbuild/BUILD/sphinx-toolbox-3.0.0/./sphinx_toolbox/more_autodoc/typehints.py", line 231, in <module>
    builder_ready = sphinx_autodoc_typehints.builder_ready
AttributeError: module 'sphinx_autodoc_typehints' has no attribute 'builder_ready'

Exception occurred:
  File "/home/tkloczko/rpmbuild/BUILD/sphinx-toolbox-3.0.0/./sphinx_toolbox/more_autodoc/typehints.py", line 231, in <module>
    builder_ready = sphinx_autodoc_typehints.builder_ready
AttributeError: module 'sphinx_autodoc_typehints' has no attribute 'builder_ready'
The full traceback has been saved in /tmp/sphinx-err-3n2mtc97.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
```
```console
[tkloczko@devel-g2v SRPMS]$ cat /tmp/sphinx-err-3n2mtc97.log
# Sphinx version: 4.5.0
# Python version: 3.8.13 (CPython)
# Docutils version: 0.17.1 release
# Jinja2 version: 3.1.1
# Last messages:

# Loaded extensions:
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/cmd/build.py", line 272, in build_main
    app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
  File "/usr/lib/python3.8/site-packages/sphinx/application.py", line 223, in __init__
    self.setup_extension(extension)
  File "/usr/lib/python3.8/site-packages/sphinx/application.py", line 380, in setup_extension
    self.registry.load_extension(self, extname)
  File "/usr/lib/python3.8/site-packages/sphinx/registry.py", line 438, in load_extension
    metadata = setup(app)
  File "/home/tkloczko/rpmbuild/BUILD/sphinx-toolbox-3.0.0/./sphinx_toolbox/__init__.py", line 95, in setup
    app.setup_extension("sphinx_toolbox.more_autodoc.autoprotocol")
  File "/usr/lib/python3.8/site-packages/sphinx/application.py", line 380, in setup_extension
    self.registry.load_extension(self, extname)
  File "/usr/lib/python3.8/site-packages/sphinx/registry.py", line 425, in load_extension
    mod = import_module(extname)
  File "/usr/lib64/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/tkloczko/rpmbuild/BUILD/sphinx-toolbox-3.0.0/./sphinx_toolbox/more_autodoc/autoprotocol.py", line 153, in <module>
    from sphinx_toolbox.more_autodoc.generic_bases import _add_generic_bases
  File "/home/tkloczko/rpmbuild/BUILD/sphinx-toolbox-3.0.0/./sphinx_toolbox/more_autodoc/generic_bases.py", line 85, in <module>
    from sphinx_toolbox.more_autodoc.typehints import format_annotation
  File "/home/tkloczko/rpmbuild/BUILD/sphinx-toolbox-3.0.0/./sphinx_toolbox/more_autodoc/typehints.py", line 231, in <module>
    builder_ready = sphinx_autodoc_typehints.builder_ready
AttributeError: module 'sphinx_autodoc_typehints' has no attribute 'builder_ready'
```

**Comment by kloczek** [comment]
Looks like `sphinx-toolbox` 3.0.0 pytest test suite is failing with simillar errors
```console
+ PYTHONPATH=/home/tkloczko/rpmbuild/BUILDROOT/python-sphinx-toolbox-3.0.0-2.fc35.x86_64/usr/lib64/python3.8/site-packages:/home/tkloczko/rpmbuild/BUILDROOT/python-sphinx-toolbox-3.0.0-2.fc35.x86_64/usr/lib/python3.8/site-packages
+ /usr/bin/pytest -ra
=========================================================================== test session starts ============================================================================
platform linux -- Python 3.8.13, pytest-7.1.2, pluggy-1.0.0
Test session started at 01:22:33
rootdir: /home/tkloczko/rpmbuild/BUILD/sphinx-toolbox-3.0.0, configfile: tox.ini
plugins: datadir-1.3.1, regressions-2.3.1, hypothesis-6.41.0, httpserver-1.0.4, timeout-2.1.0
timeout: 600.0s
timeout method: signal
timeout func_only: False
collected 2360 items / 12 errors

================================================================================== ERRORS ==================================================================================
____________________________________________________ ERROR collecting tests/test_more_autodoc/test_autodoc_typehints.py ____________________________________________________
tests/test_more_autodoc/test_autodoc_typehints.py:52: in <module>
    from sphinx_toolbox.more_autodoc.typehints import format_annotation, process_docstring
sphinx_toolbox/more_autodoc/typehints.py:231: in <module>
    builder_ready = sphinx_autodoc_typehints.builder_ready
E   AttributeError: module 'sphinx_autodoc_typehints' has no attribute 'builder_ready'
_____________________________________________________ ERROR collecting tests/test_more_autodoc/test_autonamedtuple.py ______________________________________________________
tests/test_more_autodoc/test_autonamedtuple.py:6: in <module>
    from sphinx_toolbox.more_autodoc import autonamedtuple
sphinx_toolbox/more_autodoc/autonamedtuple.py:150: in <module>
    from sphinx_toolbox.more_autodoc.typehints import format_annotation
sphinx_toolbox/more_autodoc/typehints.py:231: in <module>
    builder_ready = sphinx_autodoc_typehints.builder_ready
E   AttributeError: module 'sphinx_autodoc_typehints' has no attribute 'builder_ready'
______________________________________________________ ERROR collecting tests/test_more_autodoc/test_autoprotocol.py _______________________________________________________
tests/test_more_autodoc/test_autoprotocol.py:6: in <module>
    from sphinx_toolbox.more_autodoc import autoprotocol
sphinx_toolbox/more_autodoc/autoprotocol.py:153: in <module>
    from sphinx_toolbox.more_autodoc.generic_bases import _add_generic_bases
sphinx_toolbox/more_autodoc/generic_bases.py:85: in <module>
    from sphinx_toolbox.more_autodoc.typehints import format_annotation
sphinx_toolbox/more_autodoc/typehints.py:231: in <module>
    builder_ready = sphinx_autodoc_typehints.builder_ready
E   AttributeError: module 'sphinx_autodoc_typehints' has no attribute 'builder_ready'
______________________________________________________ ERROR collecting tests/test_more_autodoc/test_autotypeddict.py ______________________________________________________
tests/test_more_autodoc/test_autotypeddict.py:6: in <module>
    from sphinx_toolbox.more_autodoc import autotypeddict
sphinx_toolbox/more_autodoc/autotypeddict.py:145: in <module>
    from sphinx_toolbox.more_autodoc.typehints import format_annotation
sphinx_toolbox/more_autodoc/typehints.py:231: in <module>
    builder_ready = sphinx_autodoc_typehints.builder_ready
E   AttributeError: module 'sphinx_autodoc_typehints' has no attribute 'builder_ready'
______________________________________________________ ERROR collecting tests/test_more_autodoc/test_generic_bases.py ______________________________________________________
tests/test_more_autodoc/test_generic_bases.py:6: in <module>
    from sphinx_toolbox.more_autodoc import generic_bases
sphinx_toolbox/more_autodoc/generic_bases.py:85: in <module>
    from sphinx_toolbox.more_autodoc.typehints import format_annotation
sphinx_toolbox/more_autodoc/typehints.py:231: in <module>
    builder_ready = sphinx_autodoc_typehints.builder_ready
E   AttributeError: module 'sphinx_autodoc_typehints' has no attribute 'builder_ready'
______________________________________________________ ERROR collecting tests/test_more_autodoc/test_genericalias.py _______________________________________________________
tests/test_more_autodoc/test_genericalias.py:6: in <module>
    from sphinx_toolbox.more_autodoc import genericalias
sphinx_toolbox/more_autodoc/genericalias.py:80: in <module>
    from sphinx_toolbox.more_autodoc.typehints import format_annotation
sphinx_toolbox/more_autodoc/typehints.py:231: in <module>
    builder_ready = sphinx_autodoc_typehints.builder_ready
E   AttributeError: module 'sphinx_autodoc_typehints' has no attribute 'builder_ready'
________________________________________________________ ERROR collecting tests/test_more_autodoc/test_overloads.py ________________________________________________________
tests/test_more_autodoc/test_overloads.py:6: in <module>
    from sphinx_toolbox.more_autodoc import overloads
sphinx_toolbox/more_autodoc/overloads.py:109: in <module>
    from sphinx_toolbox.more_autodoc.typehints import _resolve_forwardref, default_preprocessors, format_annotation
sphinx_toolbox/more_autodoc/typehints.py:231: in <module>
    builder_ready = sphinx_autodoc_typehints.builder_ready
E   AttributeError: module 'sphinx_autodoc_typehints' has no attribute 'builder_ready'
__________________________________________________________ ERROR collecting tests/test_more_autodoc/test_regex.py __________________________________________________________
tests/test_more_autodoc/test_regex.py:12: in <module>
    from sphinx_toolbox.more_autodoc import regex
sphinx_toolbox/more_autodoc/regex.py:157: in <module>
    from sphinx_toolbox.more_autodoc.variables import VariableDocumenter
sphinx_toolbox/more_autodoc/variables.py:132: in <module>
    from sphinx_toolbox.more_autodoc.typehints import _resolve_forwardref, format_annotation
sphinx_toolbox/more_autodoc/typehints.py:231: in <module>
    builder_ready = sphinx_autodoc_typehints.builder_ready
E   AttributeError: module 'sphinx_autodoc_typehints' has no attribute 'builder_ready'
________________________________________________________ ERROR collecting tests/test_more_autodoc/test_typehints.py ________________________________________________________
tests/test_more_autodoc/test_typehints.py:27: in <module>
    from sphinx_toolbox.more_autodoc import typehints
sphinx_toolbox/more_autodoc/typehints.py:231: in <module>
    builder_ready = sphinx_autodoc_typehints.builder_ready
E   AttributeError: module 'sphinx_autodoc_typehints' has no attribute 'builder_ready'
________________________________________________________ ERROR collecting tests/test_more_autodoc/test_typevars.py _________________________________________________________
tests/test_more_autodoc/test_typevars.py:7: in <module>
    from sphinx_toolbox.more_autodoc import typevars
sphinx_toolbox/more_autodoc/typevars.py:123: in <module>
    from sphinx_toolbox.more_autodoc.typehints import format_annotation
sphinx_toolbox/more_autodoc/typehints.py:231: in <module>
    builder_ready = sphinx_autodoc_typehints.builder_ready
E   AttributeError: module 'sphinx_autodoc_typehints' has no attribute 'builder_ready'
________________________________________________________ ERROR collecting tests/test_more_autodoc/test_variables.py ________________________________________________________
tests/test_more_autodoc/test_variables.py:11: in <module>
    from sphinx_toolbox.more_autodoc import variables
sphinx_toolbox/more_autodoc/variables.py:132: in <module>
    from sphinx_toolbox.more_autodoc.typehints import _resolve_forwardref, format_annotation
sphinx_toolbox/more_autodoc/typehints.py:231: in <module>
    builder_ready = sphinx_autodoc_typehints.builder_ready
E   AttributeError: module 'sphinx_autodoc_typehints' has no attribute 'builder_ready'
____________________________________________________________ ERROR collecting tests/test_tweaks/test_tabsize.py ____________________________________________________________
ImportError while importing test module '/home/tkloczko/rpmbuild/BUILD/sphinx-toolbox-3.0.0/tests/test_tweaks/test_tabsize.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
/usr/lib64/python3.8/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_tweaks/test_tabsize.py:3: in <module>
    from pprint36 import pformat
E   ModuleNotFoundError: No module named 'pprint36'
========================================================================= short test summary info ==========================================================================
ERROR tests/test_more_autodoc/test_autodoc_typehints.py - AttributeError: module 'sphinx_autodoc_typehints' has no attribute 'builder_ready'
ERROR tests/test_more_autodoc/test_autonamedtuple.py - AttributeError: module 'sphinx_autodoc_typehints' has no attribute 'builder_ready'
ERROR tests/test_more_autodoc/test_autoprotocol.py - AttributeError: module 'sphinx_autodoc_typehints' has no attribute 'builder_ready'
ERROR tests/test_more_autodoc/test_autotypeddict.py - AttributeError: module 'sphinx_autodoc_typehints' has no attribute 'builder_ready'
ERROR tests/test_more_autodoc/test_generic_bases.py - AttributeError: module 'sphinx_autodoc_typehints' has no attribute 'builder_ready'
ERROR tests/test_more_autodoc/test_genericalias.py - AttributeError: module 'sphinx_autodoc_typehints' has no attribute 'builder_ready'
ERROR tests/test_more_autodoc/test_overloads.py - AttributeError: module 'sphinx_autodoc_typehints' has no attribute 'builder_ready'
ERROR tests/test_more_autodoc/test_regex.py - AttributeError: module 'sphinx_autodoc_typehints' has no attribute 'builder_ready'
ERROR tests/test_more_autodoc/test_typehints.py - AttributeError: module 'sphinx_autodoc_typehints' has no attribute 'builder_ready'
ERROR tests/test_more_autodoc/test_typevars.py - AttributeError: module 'sphinx_autodoc_typehints' has no attribute 'builder_ready'
ERROR tests/test_more_autodoc/test_variables.py - AttributeError: module 'sphinx_autodoc_typehints' has no attribute 'builder_ready'
ERROR tests/test_tweaks/test_tabsize.py
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 12 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
============================================================================ 12 errors in 1.90s ============================================================================
```

**Comment by gaborbernat** [comment]
All the examples you've posted seems to be calls from sphinx-toolbox. Please fill the issue there.
