### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'Message' in sphinx_autodoc_typehints.py

### ISSUE THREAD

**Issue by terrisgit** [tox-dev/sphinx-autodoc-typehints#68]
This appears to be an incompatibility with the Napoleon extension.

sphinx-autodoc-typehints version: 1.5.2     

AttributeError: 'NoneType' object has no attribute 'Message'

This could be caused by Optional[  ] .. I can't tell for certain which file it's dying in.

Message is defined as "class Message(NamedTuple)" .. not sure if that that's the problem child. The attributes of Message are docstringed like so:

```
Message.id.__doc__ = "Documentation for the id attribute"
```

Summary:

```  
File ".venv/lib/python3.6/site-packages/sphinx_autodoc_typehints.py", line 153, in process_signature
    outer = getattr(outer, clsname)
```

Log:

```
# Sphinx version: 1.8.2
# Python version: 3.6.6 (CPython)
# Docutils version: 0.14 
# Jinja2 version: 2.10
# Last messages:
#   reading sources... [ 59%] api/edcexport.engine.controller.workflow
#   
#   reading sources... [ 61%] api/edcexport.engine.model
#   
#   reading sources... [ 62%] api/edcexport.engine.model.dbexecutor
#   
#   reading sources... [ 64%] api/edcexport.engine.model.exceptions
#   
#   reading sources... [ 66%] api/edcexport.engine.model.message
#   
# Loaded extensions:
#   sphinx.ext.mathjax (1.8.2) from .venv/lib/python3.6/site-packages/sphinx/ext/mathjax.py
#   alabaster (0.7.12) from .venv/lib/python3.6/site-packages/alabaster/__init__.py
#   sphinx.ext.autodoc (1.8.2) from .venv/lib/python3.6/site-packages/sphinx/ext/autodoc/__init__.py
#   sphinx_autodoc_typehints (unknown version) from .venv/lib/python3.6/site-packages/sphinx_autodoc_typehints.py
#   sphinx.ext.napoleon (1.8.2) from .venv/lib/python3.6/site-packages/sphinx/ext/napoleon/__init__.py
Traceback (most recent call last):
  File ".venv/lib/python3.6/site-packages/sphinx/cmd/build.py", line 304, in build_main
    app.build(args.force_all, filenames)
  File ".venv/lib/python3.6/site-packages/sphinx/application.py", line 341, in build
    self.builder.build_update()
  File ".venv/lib/python3.6/site-packages/sphinx/builders/__init__.py", line 342, in build_update
    self.build(['__all__'], to_build)
  File ".venv/lib/python3.6/site-packages/sphinx/builders/__init__.py", line 360, in build
    updated_docnames = set(self.read())
  File ".venv/lib/python3.6/site-packages/sphinx/builders/__init__.py", line 468, in read
    self._read_serial(docnames)
  File ".venv/lib/python3.6/site-packages/sphinx/builders/__init__.py", line 490, in _read_serial
    self.read_doc(docname)
  File ".venv/lib/python3.6/site-packages/sphinx/builders/__init__.py", line 534, in read_doc
    doctree = read_doc(self.app, self.env, self.env.doc2path(docname))
  File ".venv/lib/python3.6/site-packages/sphinx/io.py", line 318, in read_doc
    pub.publish()
  File ".venv/lib/python3.6/site-packages/docutils/core.py", line 217, in publish
    self.settings)
  File ".venv/lib/python3.6/site-packages/docutils/readers/__init__.py", line 72, in read
    self.parse()
  File ".venv/lib/python3.6/site-packages/docutils/readers/__init__.py", line 78, in parse
    self.parser.parse(self.input, document)
  File ".venv/lib/python3.6/site-packages/sphinx/parsers.py", line 88, in parse
    self.statemachine.run(inputstring, document, inliner=self.inliner)
  File ".venv/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 171, in run
    input_source=document['source'])
  File ".venv/lib/python3.6/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File ".venv/lib/python3.6/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File ".venv/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 2753, in underline
    self.section(title, source, style, lineno - 1, messages)
  File ".venv/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 327, in section
    self.new_subsection(title, lineno, messages)
  File ".venv/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 395, in new_subsection
    node=section_node, match_titles=True)
  File ".venv/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 282, in nested_parse
    node=node, match_titles=match_titles)
  File ".venv/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 196, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File ".venv/lib/python3.6/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File ".venv/lib/python3.6/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File ".venv/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 2326, in explicit_markup
    nodelist, blank_finish = self.explicit_construct(match)
  File ".venv/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 2338, in explicit_construct
    return method(self, expmatch)
  File ".venv/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 2081, in directive
    directive_class, match, type_name, option_presets)
  File ".venv/lib/python3.6/site-packages/docutils/parsers/rst/states.py", line 2130, in run_directive
    result = directive_instance.run()
  File ".venv/lib/python3.6/site-packages/sphinx/ext/autodoc/directive.py", line 131, in run
    documenter.generate(more_content=self.content)
  File ".venv/lib/python3.6/site-packages/sphinx/ext/autodoc/__init__.py", line 819, in generate
    self.document_members(all_members)
  File ".venv/lib/python3.6/site-packages/sphinx/ext/autodoc/__init__.py", line 740, in document_members
    check_module=members_check_module and not isattr)
  File ".venv/lib/python3.6/site-packages/sphinx/ext/autodoc/__init__.py", line 1247, in generate
    all_members=all_members)
  File ".venv/lib/python3.6/site-packages/sphinx/ext/autodoc/__init__.py", line 819, in generate
    self.document_members(all_members)
  File ".venv/lib/python3.6/site-packages/sphinx/ext/autodoc/__init__.py", line 1235, in document_members
    ModuleLevelDocumenter.document_members(self, all_members)
  File ".venv/lib/python3.6/site-packages/sphinx/ext/autodoc/__init__.py", line 740, in document_members
    check_module=members_check_module and not isattr)
  File ".venv/lib/python3.6/site-packages/sphinx/ext/autodoc/__init__.py", line 806, in generate
    sig = self.format_signature()
  File ".venv/lib/python3.6/site-packages/sphinx/ext/autodoc/__init__.py", line 1018, in format_signature
    return Documenter.format_signature(self)  # type: ignore
  File ".venv/lib/python3.6/site-packages/sphinx/ext/autodoc/__init__.py", line 466, in format_signature
    self.object, self.options, args, retann)
  File ".venv/lib/python3.6/site-packages/sphinx/application.py", line 520, in emit_firstresult
    return self.events.emit_firstresult(event, self, *args)
  File ".venv/lib/python3.6/site-packages/sphinx/events.py", line 85, in emit_firstresult
    for result in self.emit(name, *args):
  File ".venv/lib/python3.6/site-packages/sphinx/events.py", line 80, in emit
    results.append(callback(*args))
  File ".venv/lib/python3.6/site-packages/sphinx_autodoc_typehints.py", line 153, in process_signature
    outer = getattr(outer, clsname)
AttributeError: 'NoneType' object has no attribute 'Message'
```

**Comment by agronholm** [comment]
Do you have a sample project that exhibits this problem? If not, I don't think I can help you.

**Comment by terrisgit** [comment]
Understood. Does anyone use this extension with mypy?

**Comment by terrisgit** [comment]
The fix was to use Python 3.7.2

**Comment by terrisgit** [comment]
This issue is back in the latest version of Napoleon and Sphinx.

**Comment by terrisgit** [comment]
```
from typing import Optional, NamedTuple
from datetime import datetime

class Message(NamedTuple):
  """A data class representing a message to be sent.
     All dates are in UTC.
  """
  message_id: int
  uuid: str
  read_from_db: bool = False
  created: Optional[datetime] = None
  service_version: Optional[str] = None
  service_hostname: Optional[str] = None
  sponsor_id: Optional[int] = None
  sponsor_name: Optional[str] = None
  trial_id: Optional[int] = None
  trial_name: Optional[str] = None
  account_id: Optional[int] = None
  trial_account_id: Optional[int] = None
  state: Optional[str] = None
  state_reason: Optional[str] = None
  # Type is a reserved word, so message_type is preferable
  message_type: Optional[str] = None
  from_nora: Optional[str] = None
  to_edc: Optional[str] = None
  from_edc: Optional[str] = None
  error_summary: Optional[str] = None
  error_details: Optional[str] = None
  send_begin: Optional[datetime] = None
  send_attempts: Optional[int] = None
  notify_state: Optional[str] = None
  notify_target: Optional[str] = None
  endpoint_id: Optional[int] = None
  endpoint_state: Optional[str] = None
  endpoint_edc_type: Optional[str] = None
  endpoint_uri: Optional[str] = None
  endpoint_username: Optional[str] = None
  endpoint_password: Optional[str] = None
  endpoint_timeout: Optional[int] = None
  endpoint_email_from: Optional[str] = None
  endpoint_email_reply_to: Optional[str] = None
  endpoint_admin_email: Optional[str] = None
  endpoint_status_channel: Optional[str] = None
  endpoint_error_channel: Optional[str] = None
  endpoint_credentials: Optional[str] = None
  endpoint_credentials_hash: Optional[str] = None


Message.message_id.__doc__ = """Identifies a message row (in the EdcMessage table)"""
Message.uuid.__doc__ = """A unique ID assigned to the message when it was first processed"""
Message.read_from_db.__doc__ = """True if this object can be read from the database
  after a retryable error occurs"""
Message.created.__doc__ = """When the message was added to EdcMessage"""
Message.service_version.__doc__ = """Version of the service that last processed the message"""
Message.service_hostname.__doc__ = """Host name on which the service was running when the message
was last processed"""
Message.sponsor_id.__doc__ = """Identifies the sponsor (in the Sponsor table)"""
Message.sponsor_name.__doc__ = """Sponsor name"""
Message.trial_id.__doc__ = """Identifies the trial (in the Trial table)"""
Message.trial_name.__doc__ = """Trial name"""
Message.account_id.__doc__ = """Identifies the account (in the Account table)"""
Message.trial_account_id.__doc__ = """Identifies the trial account (a row in the TrialAccount
table). This is analogous to a study subject"""
Message.state.__doc__ = """Which processing state that the message is currently in. A value from
the message state enumeration."""
Message.state_reason.__doc__ = """Further describes the current value of the
state attribute. A value from the message state reason enumeration."""
Message.message_type.__doc__ = """A value from the message type enumeration"""
Message.from_nora.__doc__ = """Data from NORA to be sent to the EDC"""
Message.to_edc.__doc__ = """Data to be sent to the EDC. This is the result of transforming
rom_nora."""
Message.from_edc.__doc__ = """Response (JSON format) from the EDC after sending to_edc to it"""
Message.error_summary.__doc__ = """Last error encountered while processing the message, in short
form"""
Message.error_details.__doc__ = """Last error encountered while processing the message, in long
form"""
Message.send_begin.__doc__ = """When to_edc was last sent to the EDC"""
Message.send_attempts.__doc__ = """Number of times to_edc was sent to the EDC"""
Message.notify_state.__doc__ = """Notification state that the message is currently in. A value
from the notify state enumeration."""
Message.notify_target.__doc__ = """Specifies where to send a notification. A value from the notify
target enumeration."""
Message.endpoint_id.__doc__ = """Identifies the trial edc endpoint (a row in the TrialEdcEndpoint
table)"""
Message.endpoint_state.__doc__ = """State of the EDC endpoint. A value from the edc state
enumeration."""
Message.endpoint_edc_type.__doc__ = """A value from the EDC Type enumeration"""
Message.endpoint_uri.__doc__ = """The endpoint of the EDC to which to_edc is sent"""
Message.endpoint_username.__doc__ = """User name to use when authenticating to the EDC"""
Message.endpoint_password.__doc__ = """Encrypted password corresponding to endpoint_username"""
Message.endpoint_timeout.__doc__ = """maximum number of seconds to wait for a response from the
EDC"""
Message.endpoint_email_from.__doc__ = """"from" address to use when sending an alert email"""
Message.endpoint_email_reply_to.__doc__ = """"reply to" address to use when sending an alert
email"""
Message.endpoint_admin_email.__doc__ = """Email address to which to send an alert when an error
occurs"""
Message.endpoint_status_channel.__doc__ = """Slack channel to which to send a status update when
a message is successfully sent to an EDC, etc."""
Message.endpoint_error_channel.__doc__ = """Slack channel to which to send an alert when an
error occurs"""
Message.endpoint_credentials.__doc__ = """Encrypted credentials"""
Message.endpoint_credentials_hash.__doc__ = """SHA256 hash of :py:attr:`~endpoint_credentials`"""
```

**Comment by terrisgit** [comment]
conf.py

```
# This Sphinx configuration file was created by
# sphinx-quickstart on Mon Apr 16 21:22:43 2012.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# http://www.sphinx-doc.org/en/master/config

__version__ = "1.0.0"

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
# import os
# import sys
# sys.path.insert(0, os.path.abspath('.'))

# -- Project information -----------------------------------------------------

project = 'Export Service'
copyright = '2018, 2019.'
author = 'Inc.'

version_parts = __version__.split('.')
version = f"{version_parts[0]}.{version_parts[1]}"
# The full version, including alpha/beta/rc tags.
release = f"{__version__}"

# -- General configuration -----------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
# ACME Begin
# imgconverter is for SVG and requires Imagemagick to be installed separately and is
# specifically for PDF generation
extensions = ['sphinx.ext.autodoc', 'sphinx.ext.napoleon', 'sphinx.ext.imgconverter','sphinx.ext.todo', 'recommonmark', 'sphinx_autodoc_typehints']
 
#napoleon_use_param = False
#napoleon_use_ivar = True
napoleon_include_special_with_doc = True  # Document __special__ methods
napoleon_include_private_with_doc = True  # Document methods and attributes that start with _
napoleon_use_rtype = True # Use return type specified using mypy
# ACME End

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# ACME Begin
# The suffix of source filenames.
source_suffix = ['.rst', '.md']
# ACME End

# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = []

# -- Options for HTML output ---------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
# ACME
html_theme = 'sphinx_rtd_theme'

# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
# ACME Begin
html_static_path = ['_static']

# See https://rackerlabs.github.io/docs-rackspace/tools/rtd-tables.html
html_context = {
    'css_files': [
        '_static/theme_overrides.css',  # override wide tables in RTD theme
        ],
     }
# ACME End

# ACME Begin
# -- Options for LaTeX output --------------------------------------------------

# Grouping the document tree into LaTeX files. List of tuples
# (source start file, target name, title, author, documentclass [howto/manual]).
latex_documents = [
  ('index', 'edcexportservice.tex', 'Export Service Documentation',
   'Inc.', 'manual'),
]
```

**Comment by terrisgit** [comment]
I just got the latest of every package I use and ran it on Python 3.7.2 and it worked. Closing.

**Comment by ahoereth** [comment]
Issue persists with python 3.6, couldn’t get rid of it by updating packages, only updating python resolves it.

**Comment by terrisgit** [comment]
Reopen?

**Comment by agronholm** [comment]
@terrisgit I was hoping for a minimal repo to test against. Could you provide that, please?

**Comment by gaborbernat** [comment]
Please check again with latest release and report back if the problem is still active.
